# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: travisj.nyc
#email: travisj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  husband. father. engineer. jogger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://travisj.nyc" # the base hostname & protocol for your site
twitter_username: travisj
github_username:  travisj
instagram_username:  travisj
facebook_username:  travisj

# Build settings
markdown: kramdown

gems: 
  - jekyll-paginate
  - jekyll-bootstrap-sass
  - octopress-autoprefixer
  - jemoji

paginate: 20

bootstrap:
  assets: true

custom_categories:
  fourweeks:
    cover: /images/category_fourweeks.jpg
    title: Four Weeks in Europe
    description: Rachel and I spent most of April 2014 in Europe. It was an incredible trip that took us to parts of The Netherlands, Germany, Austria, Italy, Switzerland and France. I look forward to the day when we retrace our steps and do it all again.

