# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            travisj
tagline:          'husband. father. engineer. jogger.'
description:      'professional software engineer and amateur jogger living in brooklyn. husband to @rljart, dad to @kennethgunnerjohnson, best friend to @crusherdoggy.'
url:              http://travisj.nyc
baseurl:          /

author:
  name:           'Travis Johnson'
  url:            https://twitter.com/travisj

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/travisj
